### PR TITLE
update to 5.3

### PR DESCRIPTION
**Pull request by glitchcrab**
towards giantswarm/roadmap/issues/227

if this works then i'll eat my GS baseball cap.

### CODE REVIEW

**Comment by glitchcrab** [comment]
Looks like the cap lives to see another day.

**Comment by glitchcrab** [comment]
Well this chart is technically valid but I don't know Aqua well enough to know if it will deploy properly - I've tried to retain things which look like GS-specific additions but I make no promises.

**Comment by glitchcrab** [comment]
images are in our repos: giantswarm/giantswarm/issues/14944

**Review by ced0ps — APPROVED** [review]
LGTMIT

**Review by yasn77 — APPROVED** [review]
17 commits and 41 files is a lot to review :trollface: 

Most of this looks like upstream changes so difficult to tell. But from a quick look, it looks ok :shipit:

**Comment by glitchcrab** [comment]
all charts tested and deployed to an AWS cluster successfully. I've ironed out all the issues I've found so I'm happy to merge this in.

**Pull request merged**
